# DEV
@BASE_URL=http://localhost:8080

###

POST {{BASE_URL}}/portal/signIn
Accept: application/json
Content-Type: application/json

{
  "username": "sherlock",
  "password": "password"
}

###

POST {{BASE_URL}}/portal/signOut
Accept: application/json
Content-Type: application/json

###

POST {{BASE_URL}}/portal/api/v1/user
Accept: application/json
Content-Type: application/json

{
  "username": "anas",
  "password": "p@ssw0rd",
  "name": "Anas Juwaidi Bin Mohd Jeffry"
}
